#!/usr/bine/env bash
#Checker for commandline arguments

if [ $# -lt 4 ]; then
 echo "Usage: $1 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
 exit 1
fi
#Assigning variable to a parameter
PATH_TO_FILE="$1"
IP="$2"
USERNAME="$3"
PATH_TO_SSH_KEY="$4"
#Disabling 
scp -o "StrictHostKeyChecking no" -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME@$IP:~/"
#check if file transfer is successful
if [$? -eq 0]
then
       echo "File was transfered successful"
else
       echo "Fail to transfer a file"
fi
