#!/usr/bin/env bash
#Command to install nginx on web server

sudo apt-get update
sudo apt-get install nginx
sudo ufw 'Nginx HTTP'

echo "Holberton School" | sudo tee/var/www/html/index.html

#testing nginx configuration
sudo nginx -t

sudo service nginx reload
